import React, { lazy, Suspense, useState } from 'react';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import {
  StylesProvider,
  createGenerateClassName
} from '@material-ui/core/styles';

import Progress from './components/Progress';
import Header from './components/Header';

// docs: https://reactjs.org/docs/code-splitting.html#reactlazy
const MarketingLazy = lazy(() => import('./components/MarketingApp')); // this will make sure that we only load the MarketingApp code when we want to show it
const AuthLazy = lazy(() => import('./components/AuthApp')); // this will make sure that we only load the AuthApp code when we want to show it

const generateClassName = createGenerateClassName({
  productionPrefix: 'co' // this will change the classname prefix from jss to co to avoid classname collisions
}); // only used for the styles generated by Material UI

export default () => {
  const [isSignedIn, setIsSignedIn] = useState(false);
  return (
    <BrowserRouter>
      <StylesProvider generateClassName={generateClassName}>
        <div>
          <Header
            isSignedIn={isSignedIn}
            onSignOut={() => setIsSignedIn(false)}
          />
          <Suspense fallback={<Progress />}>
            <Switch>
              <Route path='/auth'>
                <AuthLazy onSignIn={() => setIsSignedIn(true)} />
              </Route>
              <Route path='/' component={MarketingLazy} />
            </Switch>
          </Suspense>
        </div>
      </StylesProvider>
    </BrowserRouter>
  );
};
