import React, { lazy, Suspense, useState, useEffect } from 'react';
import { Router, Route, Switch, Redirect } from 'react-router-dom';
import {
  StylesProvider,
  createGenerateClassName
} from '@material-ui/core/styles';
import { createBrowserHistory } from 'history';

import Progress from './components/Progress';
import Header from './components/Header';

// docs: https://reactjs.org/docs/code-splitting.html#reactlazy
const MarketingLazy = lazy(() => import('./components/MarketingApp')); // this will make sure that we only load the MarketingApp code when we want to show it
const AuthLazy = lazy(() => import('./components/AuthApp')); // this will make sure that we only load the AuthApp code when we want to show it
const DashboardLazy = lazy(() => import('./components/DashboardApp')); // this will make sure that we only load the DashboardApp code when we want to show it

const generateClassName = createGenerateClassName({
  productionPrefix: 'co' // this will change the classname prefix from jss to co to avoid classname collisions
}); // only used for the styles generated by Material UI

const history = createBrowserHistory(); // we need access to history to be able to redirect

export default () => {
  const [isSignedIn, setIsSignedIn] = useState(false);

  useEffect(() => {
    if (isSignedIn) {
      history.push('/dashboard');
    }
  }, [isSignedIn]);

  return (
    <Router history={history}>
      <StylesProvider generateClassName={generateClassName}>
        <div>
          <Header
            isSignedIn={isSignedIn}
            onSignOut={() => setIsSignedIn(false)}
          />
          <Suspense fallback={<Progress />}>
            <Switch>
              <Route path='/auth'>
                <AuthLazy onSignIn={() => setIsSignedIn(true)} />
              </Route>
              <Route path='/dashboard'>
                {!isSignedIn && <Redirect to='/' />}
                <DashboardLazy />
              </Route>
              <Route path='/' component={MarketingLazy} />
            </Switch>
          </Suspense>
        </div>
      </StylesProvider>
    </Router>
  );
};
